### ISSUE TITLE
Failed to exec gaze script

### ISSUE THREAD

**Issue by jespa007** [visualcamp/seeso-sample-web#1]
Hi there,
I'm trying to run the example you provided but it fails. Here the log when I'm trying to execute `npm run gaze`

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'gaze'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'pregaze', 'gaze', 'postgaze' ]
5 info lifecycle SeeSoWebSample@0.0.1~pregaze: SeeSoWebSample@0.0.1
6 info lifecycle SeeSoWebSample@0.0.1~gaze: SeeSoWebSample@0.0.1
7 verbose lifecycle SeeSoWebSample@0.0.1~gaze: unsafe-perm in lifecycle true
8 verbose lifecycle SeeSoWebSample@0.0.1~gaze: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\braingaze\src\develop\libs\js\seeso-sample-web-main\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft SDKs\Windows Azure\CLI\wbin;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Tobii\Tobii EyeX Controller\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;c:\apps\python376;C:\apps\Python376\Scripts;C:\apps\script\lua;c:\Windows\Microsoft.NET\Framework\v4.0.30319;C:\apps\script\squirrel\squirrel3\bin;C:\Windows\System32\WindowsPowerShell\v1.0\;c:\apps\script\lua;c:\apps\script\squirrel3;C:\braingaze\src\develop\BGazeTools\scripts;C:\Program Files (x86)\Java\jre1.8.0_131\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;c:\apps\web\xampp\mysql\bin;C:\Program Files\doxygen\bin;C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin;C:\Program Files\SafeNet\Authentication\SAC\x64;C:\Program Files\SafeNet\Authentication\SAC\x32;C:\apps\maths\R\R-3.6.1\bin;C:\apps\cmake\bin;C:\apps\ilmerge;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files (x86)\BrainGaze\BGazeBrowser\;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Tobii\Tobii Pro X3-120\;C:\Program Files\7invensun\A3_Runtime\bin;C:\Program Files (x86)\BrainGaze\BGazePlayer\;C:\Program Files\dotnet\;C:\Program Files\BrainGaze\BGazeBrowser\;c:\apps\script\lua;C:\apps\script\squirrel;C:\apps\script\wren;C:\Program Files\Git\cmd;C:\Program Files (x86)\HP\IdrsOCR_15.2.10.1;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\apps\web\redis;C:\apps\terminal\console;C:\Users\JESPADA-MSI\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\JESPADA-MSI\AppData\Roaming\Composer\vendor\bin;C:\apps\msys64\usr\bin;C:\apps\mingw64\bin;C:\apps\msys64\mingw32\bin;C:\apps\web\xampp\php;C:\apps\emscripten;C:\apps\cmake\bin;C:\braingaze\src\develop\BGazePlayer\3rdparty\bin;C:\Program Files\7-Zip;C:\Program Files\Aseprite;C:\Users\JESPADA-MSI\.dotnet\tools;C:\apps\script\lua;C:\apps\script\squirrel\squirrel3\sq;C:\apps\nvidia\bin;C:\Users\JESPADA-MSI\AppData\Roaming\npm
9 verbose lifecycle SeeSoWebSample@0.0.1~gaze: CWD: C:\braingaze\src\develop\libs\js\seeso-sample-web-main
10 silly lifecycle SeeSoWebSample@0.0.1~gaze: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'NODE_ENV=development parcel samples/gaze/index.html --open --port 8082'
10 silly lifecycle ]
11 silly lifecycle SeeSoWebSample@0.0.1~gaze: Returned: code: 1  signal: null
12 info lifecycle SeeSoWebSample@0.0.1~gaze: Failed to exec gaze script
13 verbose stack Error: SeeSoWebSample@0.0.1 gaze: `NODE_ENV=development parcel samples/gaze/index.html --open --port 8082`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid SeeSoWebSample@0.0.1
15 verbose cwd C:\braingaze\src\develop\libs\js\seeso-sample-web-main
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "gaze"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error SeeSoWebSample@0.0.1 gaze: `NODE_ENV=development parcel samples/gaze/index.html --open --port 8082`
22 error Exit status 1
23 error Failed at the SeeSoWebSample@0.0.1 gaze script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

My OS is Windows 7 x64 and I'm using nodejs 13.14. Do you know what is the problem ?

**Comment by jespa007** [comment]
In fact the issue was due NODE_ENV,

```
C:\braingaze\src\develop\libs\js\seeso-sample-web-main>npm run gaze

> SeeSoWebSample@0.0.1 gaze C:\braingaze\src\develop\libs\js\seeso-sample-web-main
> NODE_ENV=development parcel samples/gaze/index.html --open --port 8082

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! SeeSoWebSample@0.0.1 gaze: `NODE_ENV=development parcel samples/gaze/index.html --open --port 8082`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the SeeSoWebSample@0.0.1 gaze script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\JESPADA-MSI\AppData\Roaming\npm-cache\_logs\2021-05-08T16_35_04_784Z-debug.log
```

That was solved, by installing `win-node-env` by doing

`npm install -g win-node-env`

and the problem was solved :-)
